# Generated by Django 3.1.3 on 2020-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.CharField(max_length=600),
        ),
    ]
