# Generated by Django 3.1.3 on 2020-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201127_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1000)),
                ('img', models.ImageField(default='static/images/logo.png', upload_to='images')),
            ],
        ),
    ]
