# Generated by Django 3.1.3 on 2020-11-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='eventpage',
        ),
    ]
