# Generated by Django 3.1.3 on 2020-11-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201127_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='info',
            new_name='infos',
        ),
    ]
