# Generated by Django 3.1.3 on 2020-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201127_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventpage',
            new_name='event',
        ),
    ]
