# Generated by Django 3.1.3 on 2020-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201130_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idcard',
            field=models.CharField(default='010', max_length=10),
        ),
    ]
