# Generated by Django 3.1.3 on 2020-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201202_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
                ('img', models.ImageField(default='static/images/logo.png', upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
