# Generated by Django 3.1.3 on 2020-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201203_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
