# Generated by Django 3.1.3 on 2020-12-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='NO LINK AVAILABLE', max_length=1000),
        ),
    ]
