# Generated by Django 3.1.3 on 2020-12-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10000)),
                ('img', models.ImageField(default='static/images/logo.png', upload_to='images')),
            ],
        ),
    ]
