# Generated by Django 3.1.3 on 2020-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201203_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10000)),
                ('link', models.CharField(default='NO LINK AVAILABLE', max_length=1000)),
                ('img', models.ImageField(default='static/images/logo.png', upload_to='images')),
            ],
        ),
    ]
