# Generated by Django 3.1.3 on 2020-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201204_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idcard',
            field=models.CharField(default='100', max_length=10),
        ),
    ]
