# Generated by Django 3.1.3 on 2020-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='NOT YET POSTED MY ABOUT', max_length=50000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='static/images/dlogo.jpeg', upload_to='images'),
        ),
    ]
